[program:freshclam]
command=/usr/bin/freshclam -d -c 6
autorestart=true
priority=5
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:clamd]
command=/usr/sbin/clamd --foreground=true
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr