// Placeholder for generated API types
// This file will be generated by openapi-typescript from the NestJS Swagger documentation

export interface ApiError {
  message: string
  statusCode: number
  error?: string
}

export interface PaginatedResponse<T> {
  data: T[]
  total: number
  page: number
  limit: number
  totalPages: number
}

export interface ApiResponse<T> {
  data: T
  message?: string
}