#!/usr/bin/env ts-node
/**
 * Generate TypeScript type definitions from i18n JSON files
 * This enables IntelliSense and compile-time safety for translation keys
 * 
 * Usage: ts-node scripts/generate-i18n-types.ts
 */

import fs from 'fs';
import path from 'path';

// Resolve paths from project root (works for both CJS and ESM/ts-node)
const ROOT_DIR = path.resolve(process.cwd());
const LOCALES_DIR = path.join(ROOT_DIR, 'packages/translations/locales/en');
const OUTPUT_FILE = path.join(ROOT_DIR, 'frontend/i18n/types.ts');

interface TranslationObject {
  [key: string]: string | TranslationObject;
}

/**
 * Flatten nested translation objects into dot-notation keys
 */
function flattenKeys(obj: TranslationObject, prefix = '', result: string[] = []): string[] {
  for (const [key, value] of Object.entries(obj)) {
    const newKey = prefix ? `${prefix}.${key}` : key;
    
    if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      flattenKeys(value, newKey, result);
    } else {
      result.push(newKey);
    }
  }
  
  return result;
}

/**
 * Generate TypeScript type definitions from translation files
 */
function generateTypes(): void {
  console.log('🔧 Generating i18n TypeScript types...\n');

  if (!fs.existsSync(LOCALES_DIR)) {
    console.error(`❌ Error: Locales directory not found: ${LOCALES_DIR}`);
    process.exit(1);
  }

  const files = fs.readdirSync(LOCALES_DIR).filter(f => f.endsWith('.json'));
  
  if (files.length === 0) {
    console.error(`❌ Error: No JSON files found in ${LOCALES_DIR}`);
    process.exit(1);
  }

  const allKeys: string[] = [];
  const namespaceKeys: Record<string, string[]> = {};

  // Process each namespace file
  for (const file of files) {
    const namespace = file.replace('.json', '');
    // Guard against accidental ".json" file -> empty namespace.
    if (!namespace) {
      console.warn(`⚠️  Skipping invalid namespace file: ${file}`);
      continue;
    }
    const filePath = path.join(LOCALES_DIR, file);
    
    try {
      const content = fs.readFileSync(filePath, 'utf8');
      const translations: TranslationObject = JSON.parse(content);
      
      // Get all keys for this namespace
      const keys = flattenKeys(translations);
      namespaceKeys[namespace] = keys;
      
      // Add namespaced keys (ns:key format)
      keys.forEach(key => {
        allKeys.push(`${namespace}:${key}`);
      });
      
      console.log(`✅ ${namespace}.json - ${keys.length} keys`);
    } catch (error) {
      console.error(`❌ Error processing ${file}:`, error);
      process.exit(1);
    }
  }

  // Generate TypeScript file
  const typeDefinitions = generateTypeFile(allKeys, namespaceKeys);
  
  // Ensure output directory exists
  const outputDir = path.dirname(OUTPUT_FILE);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(OUTPUT_FILE, typeDefinitions, 'utf8');

  console.log(`\n✨ Generated ${allKeys.length} typed translation keys`);
  console.log(`📝 Output: ${OUTPUT_FILE}`);
  console.log('\n💡 Usage:');
  console.log('   import type { I18nKey, NamespaceKey } from "@/i18n/types";');
  console.log('   const key: I18nKey = "common:buttons.login"; // ✅ Type-safe!');
}

/**
 * Generate the TypeScript type definition file content
 */
function generateTypeFile(allKeys: string[], namespaceKeys: Record<string, string[]>): string {
  const timestamp = new Date().toISOString();
  
  let content = `/**
 * Auto-generated i18n type definitions
 * Generated: ${timestamp}
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Run: npm run generate:i18n-types
 */

// Union type of all available translation keys with namespace prefix
export type I18nKey =
${allKeys.map(key => `  | '${key}'`).join('\n')};

`;

  // Generate per-namespace types
  for (const [namespace, keys] of Object.entries(namespaceKeys)) {
    const typeName = namespace.charAt(0).toUpperCase() + namespace.slice(1) + 'Key';
    content += `// Keys available in ${namespace} namespace\n`;
    if (!keys || keys.length === 0) {
      content += `export type ${typeName} = never;\n\n`;
    } else {
      content += `export type ${typeName} =\n`;
      content += keys.map(key => `  | '${key}'`).join('\n');
      content += ';\n\n';
    }
  }

  // Add namespace type
  const namespaces = Object.keys(namespaceKeys);
  content += `// Available namespaces\n`;
  content += `export type I18nNamespace =\n`;
  content += namespaces.map(ns => `  | '${ns}'`).join('\n');
  content += ';\n\n';

  // Add helper type for namespaced keys
  content += `// Helper type for keys within a specific namespace\n`;
  content += `export type NamespaceKey<NS extends I18nNamespace> = Extract<I18nKey, \`\${NS}:\${string}\`>;\n\n`;

  // Add usage example
  content += `/**
 * Usage Examples:
 * 
 * 1. Type-safe translation function:
 *    const t = (key: I18nKey) => i18n.t(key);
 * 
 * 2. Namespace-specific keys:
 *    const key: CommonKey = 'buttons.login';
 * 
 * 3. With useTranslation hook:
 *    const { t } = useTranslation<I18nNamespace>(['common', 'auth']);
 */\n`;

  return content;
}

// Run the generator
generateTypes();
