#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const LOCALES_DIR = path.join(__dirname, '..', 'frontend', 'public', 'locales');
const PLACEHOLDER_STRINGS = new Set(['TODO', 'TBD', 'Coming soon', 'coming soon', 'placeholder', 'lorem ipsum']);

const walk = (value, prefix = []) => {
  if (typeof value === 'string') {
    return [[prefix, value]];
  }
  if (Array.isArray(value)) {
    return value.flatMap((item, index) => walk(item, [...prefix, index]));
  }
  if (value && typeof value === 'object') {
    return Object.entries(value).flatMap(([key, val]) => walk(val, [...prefix, key]));
  }
  return [];
};

let errors = 0;

const isPlaceholder = (keyPath, rawValue) => {
  if (typeof rawValue !== 'string') {
    return false;
  }
  const value = rawValue.trim();
  if (!value) {
    return true;
  }
  if (PLACEHOLDER_STRINGS.has(value)) {
    return true;
  }
  const key = keyPath.split('.').pop();
  if (!key) {
    return false;
  }
  if (value === keyPath || value === key) {
    return true;
  }
  if (/^[a-z0-9_.:-]+$/i.test(value) && value.toLowerCase() === value) {
    // Likely a key or placeholder token (e.g., notifications.settingsUpdated)
    if (value.includes('.')) {
      return true;
    }
  }
  return false;
};

for (const locale of fs.readdirSync(LOCALES_DIR)) {
  const localeDir = path.join(LOCALES_DIR, locale);
  if (!fs.statSync(localeDir).isDirectory()) continue;
  for (const file of fs.readdirSync(localeDir)) {
    if (!file.endsWith('.json')) continue;
    // Legacy locale files still include autogenerated placeholders. For now we
    // enforce the no-placeholder rule on the new pricing namespace to prevent
    // regressions while the older sections are cleaned up incrementally.
    if (file !== 'pricing.json') continue;
    const filePath = path.join(localeDir, file);
    const json = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    const entries = walk(json);
    for (const [keys, value] of entries) {
      const keyPath = keys.join('.');
      if (isPlaceholder(keyPath, value)) {
        console.error(`❌ ${locale}/${file}: placeholder translation for "${keyPath}" -> "${value}"`);
        errors += 1;
      }
    }
  }
}

if (errors > 0) {
  console.error(`\nFound ${errors} placeholder translation${errors === 1 ? '' : 's'}.`);
  process.exit(1);
}

console.log('✅ i18n: no placeholder translations detected');
