#!/bin/bash
set -e

echo "🚀 Starting Render build process..."

# Check for required environment variables
if [ -z "$DATABASE_URL" ]; then
    echo "⚠️  DATABASE_URL not set - migrations will run at application startup"
    exit 0
fi

# Verify Prisma client exists (should be generated by postinstall)
if [ ! -d "../node_modules/@prisma/client" ]; then
    echo "⚠️  Prisma client not found, generating..."
    npx prisma generate
fi

echo "🔧 Resolving any failed migrations..."
npx prisma migrate resolve --rolled-back 20251030_comprehensive_schema_audit_fix 2>/dev/null || echo "No failed migrations to resolve"
npx prisma migrate resolve --rolled-back 20251030_add_stripe_customer_id_if_missing 2>/dev/null || echo "No other failed migrations"

echo "📊 Current migration status:"
npx prisma migrate status || echo "Could not get migration status"

echo "🔄 Deploying database migrations..."
if npx prisma migrate deploy; then
    echo "✅ Migrations deployed successfully"
else
    echo "❌ Migration deployment failed"
    echo "📋 Checking what went wrong..."
    npx prisma migrate status
    echo "⚠️  Continuing build despite migration failure..."
fi

echo "✅ Build preparation complete!"